# Generated by Django 3.1 on 2020-08-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(verbose_name='date_time')),
                ('reg_no', models.CharField(max_length=20)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_colour', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('staff_name', models.CharField(max_length=50)),
                ('additional_notes', models.TextField()),
            ],
        ),
    ]
