# Generated by Django 3.1 on 2020-08-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_offs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveoff',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='driveoff',
            name='vehicle_colour',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='driveoff',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driveoff',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
