# Generated by Django 3.1 on 2020-08-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_offs', '0002_auto_20200818_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveoff',
            name='data_time',
            field=models.DateTimeField(verbose_name='date and time'),
        ),
        migrations.AlterField(
            model_name='driveoff',
            name='reg_no',
            field=models.CharField(max_length=20, verbose_name='Registration no'),
        ),
        migrations.AlterField(
            model_name='driveoff',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='vehicle type (eg: Car)'),
        ),
    ]
