# Generated by Django 3.1 on 2020-08-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_offs', '0003_auto_20200818_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveoff',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Transaction Amount £'),
        ),
    ]
