# Generated by Django 3.1 on 2020-08-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_offs', '0004_auto_20200818_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveoff',
            options={'ordering': ['date_time']},
        ),
        migrations.RenameField(
            model_name='driveoff',
            old_name='data_time',
            new_name='date_time',
        ),
        migrations.AlterField(
            model_name='driveoff',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Transaction Amount (£)'),
        ),
    ]
