# Generated by Django 3.1 on 2020-08-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_offs', '0005_auto_20200818_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveoff',
            name='paid',
            field=models.BooleanField(default=1, verbose_name='Paid?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driveoff',
            name='police_reference',
            field=models.CharField(blank=True, max_length=20, verbose_name='police reference no:'),
        ),
        migrations.AlterField(
            model_name='driveoff',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Transaction amount (£)'),
        ),
    ]
