# Generated by Django 3.1 on 2020-08-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_offs', '0006_auto_20200821_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveoff',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='driveoff',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Paid Date'),
        ),
    ]
